name: Build and Push to Docker Hub

on:
  push:
    branches: ["main"] # Runs every time you push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push Gateway
        uses: docker/build-push-action@v4
        with:
          context: ./gateway-service
          push: true
          tags: dhiraj918106/gateway-service:latest
      
      - name: Build and Push Worker
        uses: docker/build-push-action@v4
        with:
          context: ./worker-service
          push: true
          tags: dhiraj918106/worker-service:latest

